### PR TITLE
fixes GEARPUMP-156 Replace logo in site, GitHub, Travis, etc

### PR DESCRIPTION
**Pull request by kkasravi**

### CODE REVIEW

**Comment by kkasravi** [comment]
@manuzhang can you +1 so I can get the logo in and see how it looks?

**Comment by manuzhang** [comment]
+1

**Comment by huafengw** [comment]
Seems the logo is too large:(

**Comment by kkasravi** [comment]
@huafengw fixed in GEARPUMP-159 (https://github.com/apache/incubator-gearpump/pull/47)

**Pull request closed without merging**
