### PR TITLE
[GEARPUMP-280] Set MAX_TIME_MILLIS to Long.MaxValue minus 1

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the commit message is formatted like:
   `[GEARPUMP-<Jira issue #>] Meaningful description of pull request` 
 - [x] Make sure tests pass via `sbt clean test`.
 - [x] Make sure old documentation affected by the pull request has been updated and new documentation added for new functionality.

### CODE REVIEW

**Comment by manuzhang** [comment]
R: @huafengw

**Comment by huafengw** [comment]
Can you give some backgrounds?

**Comment by manuzhang** [comment]
For any message to be sent out, its `timestamp` should be within the `LifeTime` of a Task. The `LifeTime` is of range `[birth, death)` where `death` is excluding. Currently, the maximum values of both `timestamp` and `death` are `Long.MaxValue` in milliseconds. Consequently, message with the maximum timestamp can't be sent out.

**Comment by huafengw** [comment]
+1

**Comment by manuzhang** [comment]
Build passed at https://travis-ci.org/manuzhang/incubator-gearpump/builds/204850826

**Pull request closed without merging**
