### PR TITLE
fix GEARPUMP-144 make the user for HDFS and Yarn configurable in yarn…

### PR DESCRIPTION
**Pull request by huafengw**
…client

### CODE REVIEW

**Comment by huafengw** [comment]
@karol-brejna-i 
Hi Karol, please help to review this pr.

**Comment by manuzhang** [comment]
@karol-brejna-i any updates ?

**Comment by manuzhang** [comment]
+1

**Comment by karol-brejna-i** [comment]
+1
works fine. 
also, in our new environments logs started to work properly (probably this and previous change helped). i closed the other ticket, too.

**Pull request closed without merging**
