### PR TITLE
Fixes GEARPUMP-18 Enable publishing gearpump artifacts to repository.…

### PR DESCRIPTION
**Pull request by kkasravi**
…apache.org

### CODE REVIEW

**Comment by manuzhang** [comment]
+1. The UT failure is already fixed in https://git-wip-us.apache.org/repos/asf?p=incubator-gearpump.git;a=commit;h=83b36ef76de786534fe92a6d75149d4d561915f4 but the sync gets stuck somehow.

**Comment by manuzhang** [comment]
Do we need to update pgp info ?

**Comment by kkasravi** [comment]
i think we're ok.

**Comment by manuzhang** [comment]
+1

**Pull request closed without merging**
