### PR TITLE
[GEARPUMP-330] Allow examples to run in `sbt run` and Intellij

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the commit message is formatted like:
   `[GEARPUMP-<Jira issue #>] Meaningful description of pull request` 
 - [x] Make sure tests pass via `sbt clean test`.
 - [x] Make sure old documentation affected by the pull request has been updated and new documentation added for new functionality.

### CODE REVIEW

**Comment by huafengw** [comment]
Document update?

**Comment by manuzhang** [comment]
which part do you mean ?

**Comment by darionyaphet** [comment]
maybe not only *gearpump-core* and *gearpump-streaming* should change to **compile** .

**Comment by manuzhang** [comment]
@darionyaphet what else then ?

**Comment by manuzhang** [comment]
@huafengw Added docs to quick start with `sbt run`

**Comment by huafengw** [comment]
LGTM

**Comment by manuzhang** [comment]
@darionyaphet please open new jira/pr if you find other build settings require change

**Pull request closed without merging**
