### PR TITLE
[GEARPUMP-336] Add scalac options and fix warnings

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the commit message is formatted like:
   `[GEARPUMP-<Jira issue #>] Meaningful description of pull request` 
 - [ ] Make sure tests pass via `sbt clean test`.
 - [x] Make sure old documentation affected by the pull request has been updated and new documentation added for new functionality.

### CODE REVIEW

**Comment by manuzhang** [comment]
R: @huafengw

**Comment by huafengw** [comment]
LGTM, is the failure related?

**Comment by manuzhang** [comment]
@huafengw Seems. Anyway, I've pushed more fixes and re-trigger travis.

**Comment by huafengw** [comment]
Looks like the code style all passed, but the test still failed, which is weird.

**Pull request closed without merging**
