### PR TITLE
fix GEARPUMP161 application logs are located in wrong place on Yarn

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

**Comment by manuzhang** [comment]
@karol-brejna-i could you check this pr in your environment ?

**Comment by karol-brejna-i** [comment]
Sure, will do. I assigned the jira to me.

**Comment by kkasravi** [comment]
@karol-brejna-i let me know (with +1) and i can merge or you can. Thanks

**Comment by karol-brejna-i** [comment]
We met with @huafengw today. Something is still wrong. Huafeng is trying to peproduce. 

I am updating jira as new info arrives. Will update the pull request comments, too.

**Comment by kkasravi** [comment]
Thanks. @karol-brejna-i

**Comment by huafengw** [comment]
Unfortunately, I can't reproduce the problem, here is what I've done:
I work with gearpump 0.8.0 and included the change. I launch the yarn cluster with user ```huafeng``` and launch the Gearpump cluster on Yarn with user ```gear```. And after I submit an application:
```
[huafengw@hfwdesktop hadoop-2.7.1]$ ll logs/userlogs/application_1467022600765_0003/container_1467022600765_0003_01_000003/
total 72
drwxrwxr-x 3 huafengw huafengw    17 Jun 27 18:33 applicationData
-rw-rw-r-- 1 huafengw huafengw 69142 Jun 28 09:12 gearpump-worker-7301@hfwdesktop.sh.intel.com.log
-rw-rw-r-- 1 huafengw huafengw   656 Jun 27 18:31 stderr
```

**Comment by karol-brejna-i** [comment]
@huafengw could you sum up what permissions (groups) does your user belong to? Maybe it is some kind of weird permission problem...

**Comment by huafengw** [comment]
@karol-brejna-i you mean /etc/passwd and /etc/group?

**Comment by kkasravi** [comment]
+1

**Pull request closed without merging**
