### PR TITLE
[GEARPUMP-267] Changing docker image for Kafka (spotify/kafka doesn't have tag for 0.8.x)

### PR DESCRIPTION
**Pull request by karol-brejna-i**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the commit message is formatted like:
   `[GEARPUMP-<Jira issue #>] Meaningful description of pull request` 
 - [ ] Make sure tests pass via `sbt clean test`.
 - [ ] Make sure old documentation affected by the pull request has been updated and new documentation added for new functionality.

### CODE REVIEW

**Comment by karol-brejna-i** [comment]
The good news is, Kafka "cluster" is up again (during integration tests).
The bad news, there is some error running Kafka example.
I found this in application logs:
```
INFO] [02/22/2017 08:20:08.282] [Executor@app2exec1] Executor received restart tasks
[WARN] [02/22/2017 08:20:08.282] [ProducerConfig] The configuration value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer was supplied but isn't a known config.
[WARN] [02/22/2017 08:20:08.283] [ProducerConfig] The configuration key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer was supplied but isn't a known config.
[INFO] [02/22/2017 08:20:08.283] [KafkaSource] created checkpoint store for [topic3,0]
[ERROR] [02/22/2017 08:20:08.283] [Executor@app2exec1] We got java.lang.ArithmeticException from Some(TaskId(0,0)), we will treat it as MessageLoss, so that the system will replay all lost message
java.lang.ArithmeticException: long overflow
        at java.lang.Math.multiplyExact(Math.java:892)
        at java.time.Instant.toEpochMilli(Instant.java:1232)
        at org.apache.gearpump.streaming.kafka.lib.source.AbstractKafkaSource.open(AbstractKafkaSource.scala:94)
        at org.apache.gearpump.streaming.source.DataSourceTask.onStart(DataSourceTask.scala:71)
        at org.apache.gearpump.streaming.task.TaskWrapper.onStart(TaskWrapper.scala:96)
        at org.apache.gearpump.streaming.task.TaskActor.onStart(TaskActor.scala:107)
        at org.apache.gearpump.streaming.task.TaskActor.org$apache$gearpump$streaming$task$TaskActor$$onStartClock(TaskActor.scala:195)
        at org.apache.gearpump.streaming.task.TaskActor$$anonfun$waitForStartClock$1.applyOrElse(TaskActor.scala:212)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
        at org.apache.gearpump.streaming.task.TaskActor.aroundReceive(TaskActor.scala:42)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[WARN] [02/22/2017 08:20:08.284] [OneForOneStrategy] long overflow
[INFO] [02/22/2017 08:20:08.285] [DataSourceTask@app2exec1TaskId(0,0)] closing data source...
[INFO] [02/22/2017 08:20:08.283] [DataSinkTask@app2exec1TaskId(1,0)] closing data sink...
```

**Comment by huafengw** [comment]
@manuzhang Looks like it's related to the timestamp

**Comment by karol-brejna-i** [comment]
Probably related to 
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#toEpochMilli--

The logs show:
`[INFO] [02/22/2017 10:25:34.395] [KafkaSource] KafkaSource opened at start time -292275055-05-16T16:47:04.192Z`
Then it looks like converting it in AbstractKafkaSource.open() fails:
`maybeRecover(startTime.toEpochMilli)`

**Comment by karol-brejna-i** [comment]
On the other hand converting fron tihs date works on my dev machine:
```
import java.time.Instant
type TimeStamp = Long
val MIN_TIME_MILLIS: Long = Long.MinValue
var _minClock: TimeStamp = MIN_TIME_MILLIS
val startTime = Instant.ofEpochMilli(_minClock)
val result = startTime.toEpochMilli
```

**Comment by manuzhang** [comment]
What's your jdk version ? Looks like hitting https://bugs.openjdk.java.net/browse/JDK-8074032

**Comment by karol-brejna-i** [comment]
I used Java 8 from Oracle, more precisely:
``` java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
Let me upgrade to newer version and send an update.

**Comment by karol-brejna-i** [comment]
gearump-launcher that we use in integration tests uses errordeveloper/oracle-jre image that has JDK 8u45-b14. I updated JRE image and will use it in gearpump-launcher to see if new version of Java fixes the tests.

**Comment by karol-brejna-i** [comment]
I've collected docker definitions in one place (integrationtest/docker), upgraded java version for gearpump-launcher, switched to "our" kafka image (0.8.2.1): https://github.com/apache/incubator-gearpump/pull/162

It looks like all the integration tests pass now.

**Comment by huafengw** [comment]
Hi Karol, this pull request includes the former GEARPUMP-236 and it's also covered by your another pr, so maybe we can close this one?

**Comment by karol-brejna-i** [comment]
Now it's obsolete (implemented by two other PRs). Closing.

**Pull request closed without merging**
